- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init
  register: kubeadm_init_output
  become: true

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    dest: ./join
    src: /root/kubejoin.sh

- name: Organize files
  shell: |
        cp join/{{ inventory_hostname }}/root/kubejoin.sh join/  
        rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: false

- name: Aplicar calico.yaml
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/tigera-operator.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true