---
- name: Add k8s apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add k8s repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install k8s packages
  apt: 
    name: "{{ item }}"
  with_items: "{{ k8s_packages }}"

- name: Disable swap
  command: swapoff -a

- name: Ensure they can see bridge traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables